site_name: Mellfice Docs

theme:
  name: material
  language: ru
  features:
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Home: index.md
  - Network:
      - Обзор: Network/index.md
      - Huawei:
          - Базовая настройка VRP: Network/Huawei/index.md
  - Linux:
      - Обзор: Linux/index.md
      - Команды Linux: Linux/Команды Linux.md
  - Git:
      - Основы: Git/git.md
